### ISSUE TITLE
About Low pass filter and tuning sample

### ISSUE THREAD

**Issue by VirguleBarbare** [lykaust15/DeepSimulator#19]
Hi ! I work on Deepsimulator and I wonder why the cut off of low pass filter is 850 in default. Is it the better number to get closer to the reality ? 
Futhermore, I wonder what is the différence between the both choice of tunning sample ? 
Thank you and have a good day !

**Comment by realbigws** [comment]
Dear Virgule.

The reason why we set the parameter of the low-pass filter to 850 is based
on the fact that this parameter (combined with the other default
parameters) will lead to the simulated signals that could generate output
reads having ~92% base-calling accuracy.

If you lower down this parameter (say, to 800 or 750), you will obtain
"fuzzier" raw signals which shall reduce the base-calling accuracy to 85%
or even 80%.

Best,
-Sheng

**Comment by VirguleBarbare** [comment]
thanks for your answer. I understand for a lower cutoff, but if we choose a low pass filter to 1000 or 1200, are we closer to reality ?

**Comment by VirguleBarbare** [comment]
thanks for your answer.

And about tuen sampling ? I don't understand the difference between both parameters...

**Comment by realbigws** [comment]
On Mon, Jun 3, 2019 at 2:43 AM VirguleBarbare <notifications@github.com>
wrote:

> thanks for your answer. I understand for a lower cutoff, but if we choose
> a low pass filter to 1000 or 1200, are we closer to reality ?
>

Well, you also need to tune the other parameters, such as event_std (-e)
and noise_std (-s). You may also turn off the low-pass filter by setting " -f
0".

Suppose you want to generate a "perfect" simulated reads, please use "-P 2"
or "-e 0 -f 0 -s 0".

**Comment by VirguleBarbare** [comment]
thanks for your answer, I want to simulate sequencing that get closer to a real sequencing with a MinION sequencer. So I don't really want perfect reads.

**Comment by realbigws** [comment]
Dear Virgule,

I have generated a new version of DeepSimulator, which tries to fix a
series of minor issues, and to put a large effort for the description of
the parameters in "deep_simulator.sh".

Please find this new branch below:
https://github.com/lykaust15/DeepSimulator/tree/experiment

please check the description by typing "./deep_simulator.sh".

I'm welcome to all the new suggestions raised by you.

Best,
-Sheng

**Comment by VirguleBarbare** [comment]
Thank you very much !! I understand better now !
And about tune sampling ? I don't understand the difference between both parameters...

best.

**Comment by realbigws** [comment]
On Fri, Jun 7, 2019 at 6:18 AM VirguleBarbare <notifications@github.com>
wrote:

> Thank you very much !! I understand better now !
> And about tune sampling ? I don't understand the difference between both
> parameters...
>

Do you mean the parameter "-u tune_sampling"? If so, please find the
detailed explanation below.

According to the Oxford Nanopore Technology (ONT) official instructions,
for the current MinION chemistry, ONT reports that single DNA strands are
pulled through the pore at an average speed of 450 bases per second (bp/s),
while the electric current signal is sampled at a frequency of 4 kHz. This
means that there are on average eight to nine discrete measurements per
k-mer (or, event), although the number varies because of the fluctuating
translocation speed of the motor protein.  (according to this paper:
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1462-9).

In our previous work DeepSimulator v0.98, we have estimated the
distribution of the signal repeat times of 5-mer event (as shown in Figure
6 of our DeepSimulator paper:
https://academic.oup.com/bioinformatics/article/34/17/2899/4962495).
However, we found out that the average of this estimated distribution is
around six instead of eight. This might be due to the insufficient number
of data we used to estimate the distribution. To solve this issue, in the
current version of DeepSimulator (shall be v1.49 officially), we add this
option to finetune the signal repeat time for each event, which shall make
the average number to eight.

Experimental results indicate that the signals generated by DeepSimulator
v1.49 shall be more close to the real-world raw signals in terms of the
total sampling points. Please type the below command and you shall have a
direct understanding:

```
./deep_simulator.sh -i
example/001c577a-a502-43ef-926a-b883f94d157b.true_fasta -n -1
```

and then compare the length of the simulated signal (stored in
001c577a-a502-43ef-926a-b883f94d157b_DeepSimu/fast5/signal_preprocess_8b411e46-b1a6-4b62-bae4-eb0773f1c149.fast5)
with the ground-truth signal (put in
example/001c577a-a502-43ef-926a-b883f94d157b.raw_signal).

Hope this answer satisfies your question.

Best,
-Sheng

**Comment by VirguleBarbare** [comment]
Thank you very much ! your answer satisfies a lot my question. 
Thank you very much for your time,

Best,
Virgule
