### ISSUE TITLE
read length

### ISSUE THREAD

**Issue by rberrens** [lykaust15/DeepSimulator#22]
Is there a possibility to not change the read length but just give the deepsimulator a fasta file with different sequences and only model the errors without changing the length of the sequences?

**Comment by lykaust15** [comment]
Hi, thank you very much for your interest!

Yes, that's possible and that's exactly what we want to achieve. You can start from the second step of our three-step pipeline, as illustrated in the figure here: https://github.com/lykaust15/DeepSimulator/blob/master/example/main_graph_wsmod3.png.

You just need to modify the file 'deep_simulator.sh'. If you find the file is hard to modify because we have added some many parameters to it. You can use 'main.sh', which is more intuitive to understand than the 'deep_simulator.sh' file. 

Feel feel to let us know if you have more questions.

**Comment by lykaust15** [comment]
Hi, we have issued a major update to DeepSimulator, please refer 'case_study.sh' for the three-step pipeline of our tool.
