### ISSUE TITLE
confusion about the output

### ISSUE THREAD

**Issue by daniellezhang** [lykaust15/DeepSimulator#8]
Hi!

I now have DeepSimulator working. However, there isn't much documentation about the output files. It would be really helpful to have some specification on the individual file in the output directory.

Thanks!

**Comment by lykaust15** [comment]
Hi, thank you for your interest!
Could you specify what output you are not sure about? Most of the folder's names are self-explained.

**Comment by MeganQiu** [comment]
> Hi, thank you for your interest!
> Could you specify what output you are not sure about? Most of the folder's names are self-explained.

I am also interested in the outputs. Can we know the positions where simulated reads locate in the corresponding genomes? Are they stored in the mapping.paf ?

**Comment by daniellezhang** [comment]
It is the output of deep_simulator.sh. I figured out a few by looking at the code but just want to confirm:
samped_read.fasta is the read generated from the given genome
test.fastq is the read after processing through the pore model

And yes, same question as @MeganQiu . Can you give more clarification for mapping.paf?

**Comment by lykaust15** [comment]
> > Hi, thank you for your interest!
> > Could you specify what output you are not sure about? Most of the folder's names are self-explained.
> 
> I am also interested in the outputs. Can we know the positions where simulated reads locate in the corresponding genomes? Are they stored in the mapping.paf ?

Yes, there are stored in mapping.paf. Here is the short explanation of PAF file: https://github.com/lh3/miniasm/blob/master/PAF.md

**Comment by lykaust15** [comment]
> It is the output of deep_simulator.sh. I figured out a few by looking at the code but just want to confirm:
> sampled_read.fasta is the read generated from the given genome
> test.fastq is the read after processing through the pore model

Yes, exactly.


> And yes, same question as @MeganQiu . Can you give more clarification for mapping.paf?

Here is the short explanation of PAF file: https://github.com/lh3/miniasm/blob/master/PAF.md

**Comment by belaidH** [comment]
Hi @lykaust15 ,
In PAF output file of deepSimulator there are more column than explanation PAF what the last columns mean?
also is there anyway to fix length of read? 
And when I try to generate 100 reads there are read which is same to the reference (100%) is my simulation correct or the number of reads need to be less than 100? 

thank's

**Comment by lykaust15** [comment]
Hi, @belaidH, thank you very much for your interest!
Here is the information for your first question:
```
A PAF file may optionally contain SAM-like typed key-value pairs at the end of each line.
```
If you are asking about 'cg', that is the mapping details of two sequences.

As for the read length, if you want the sampling read length to be fixed, it is simple to achieve. However, if you want the final simulated read length to be fixed, it can be tricky because the basecaller can have indel error which can vary to simulated read length. You can consider using another basecaller which has less indel result.

I did not quite understand your last question. But I think that can happen if you set the parameter to eliminate mutations. The read number can be as many as you want.

**Comment by belaidH** [comment]
Hi  @lykaust15,
I'm a little confused with the K-mers, in your article you said that you are using 5-mers (by default)but on your pore model there is juste one file and it is for 6-mers  signals.
thank's

**Comment by lykaust15** [comment]
@belaidH Could you please open another issue if you question is not related to the topic of this issue?

Back to your question:
when we started this project, the Nanoporetech has not released the 6mer table, so we first implemented DeepSimulator using 5mer. Now since the 6mer table has been officially released, we used that as the default setting of DeepSimulator. Compared to 5mer, 6mer is more precise. 
DeepSimulator has been released for a while, we are planning a major update in the near future. And in that version, we will provide more options so that the user can choose which pore model they want to use.

Feel free to let us know or open another issue if you have more questions.

**Comment by yjx1217** [comment]
Hello,

Related with this issue. Here is the output directory that I got:
```
-rw-r--r-- 1 jxyue2 grp_liti  12M Apr 12 20:29 processed_genome
-rw-r--r-- 1 jxyue2 grp_liti 8.5M Apr 12 20:30 sampled_read.fasta
drwxr-xr-x 2 jxyue2 grp_liti  64K Apr 12 20:38 signal
drwxr-xr-x 2 jxyue2 grp_liti  64K Apr 12 20:38 align
drwxr-xr-x 2 jxyue2 grp_liti 144K Apr 12 20:39 fast5
drwxr-xr-x 3 jxyue2 grp_liti  153 Apr 12 22:26 fastq
-rw-r--r-- 1 jxyue2 grp_liti  18M Apr 12 22:27 test.fastq
-rw-r--r-- 1 jxyue2 grp_liti 2.4M Apr 12 22:27 mapping.paf
-rw-r--r-- 1 jxyue2 grp_liti   14 Apr 12 22:27 accuracy

```
Is the file "test.fastq" the fastq version of the file "sampled_read.fasta"? If so, why different prefix was used for these two files. Say I only want simualted fastq reads, should I just use "test.fastq"?
Thanks!

Best,
Jia-Xing

**Comment by lykaust15** [comment]
Hi, Jia-Xing, thank you very much for your interest and your question.
In fact, those two are different things. "sampled_read.fasta" is the result of sampling, which is the output of the first step. There is no error in that file. "test.fastq" is the final output.
